### ISSUE TITLE
404 links in the blog page

### ISSUE THREAD

**Issue by nagueva** [dbanksdesign/dbanksdesign-gatsby#17]
Hi Danny,

Navigating in your website - great content, btw - I found a bug in the [Blog page](https://dbanks.design/blog/).

The articles link have a redundant `/blog` in the "href" property, generating a `/blog/blog/*` for all links, and causing a 404.

I visited the articles using the homepage, but you probably want to fix the blog one. ;)

Cheers.

**Comment by dbanksdesign** [comment]
Should be fixed now. Thank you so much for bringing this to my attention!
